spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elearning
    username: root
    password: MySQLroot
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8181

sa-token:
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  is-log: false

